from .DummyLinear import DummyLinear

from .GlobalQuantLinearPytorch import QuantizedLinearGlobalTorch
from .RowwiseQuantLinearPytorch import QuantizedLinearRowwiseTorch

from .GlobalQuantLinearTriton import GlobalQuantLinearTriton
from .RowwiseQuantLinearTriton import RowwiseQuantLinearTriton

